name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

      - name: Deploy via rsync
        run: |
          sync -avz -e 'ssh -p ${{ secrets.SSH_PORT }}' --include='vendor/' \
            --filter=':- .gitignore' \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='src' \
            --exclude='*.config.js' \
            --exclude='package*.json' \
            --exclude='*.lock' \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/www/staging14.pealutz.me/public_html/wp-content/themes/pealutz/
